# Generated by Django 5.2.8 on 2025-12-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_is_super_stuff_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
    ]
