# Generated by Django 5.2.8 on 2025-12-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_created_by"),
    ]

    operations = []
