# Generated by Django 6.0 on 2025-12-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
